project_id = "efaohdwvitrxanzzlgew"

[functions.create-payment]
verify_jwt = false

[functions.create-tbank-payment]
verify_jwt = false

[functions.simple-robokassa]
verify_jwt = false

[functions.robokassa-payment]
verify_jwt = false

[functions.robokassa-result]
verify_jwt = false

[functions.robokassa-webhook]
verify_jwt = false
